apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-ejemplo.fullname" . }}
  labels:
    sistema: {{ .Values.sistema }}
    {{- include "chart-ejemplo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rest
      protocol: TCP
      name: rest
  selector:
    {{- include "chart-ejemplo.selectorLabels" . | nindent 4 }}
