apiVersion: v1
kind: Namespace
metadata:
  name:  backend
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/k3dvol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pv-claim
  namespace: backend
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-backend
  namespace: backend
  labels:
    tipo: backend_comun
    app: psql-backend
spec:
  selector:
    matchLabels:
      tipo: backend_comun
      app: psql-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tipo: backend_comun
        app: psql-backend
    spec:
      volumes:
        - name: psql-pv-storage
          persistentVolumeClaim:
            claimName: psql-pv-claim
      containers:
        - name: psql
          image: postgres:15-alpine
          ports:
            - name: data
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: lab
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/pgdata
          volumeMounts:
            - name: psql-pv-storage
              mountPath: /var/lib/postgresql
              subPath: pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: psql-backend
  namespace: backend
  labels:
    tipo: backend_comun
    app: psql-backend
spec:
  ports:
    - name: data
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    tipo: backend_comun
    app: psql-backend
  type: ClusterIP